version: "3.9"
services:
  sauvedocker:
    build: .
    ports:
      - "6677:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sauvedocker-data:/app/app/data
      - sauvedocker-backups:/app/app/backups
    environment:
      - APP_SECRET=rtyzrhrthryrtrh
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  sauvedocker-data:
  sauvedocker-backups:
